//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scientific_Conferences.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        public int conferenceID { get; set; }
        public string conference_name { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string venue { get; set; }
        public int scientificID { get; set; }
    
        public virtual Scientific_staff Scientific_staff { get; set; }
    }
}
