//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scientific_Conferences.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scientific_staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scientific_staff()
        {
            this.Conference = new HashSet<Conference>();
        }
    
        public int scientificID { get; set; }
        public string surname_scientific { get; set; }
        public string name_scientific { get; set; }
        public string academic_degree { get; set; }
        public int countryID { get; set; }
        public int organizationsID { get; set; }
        public string topic_report { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conference> Conference { get; set; }
        public virtual Country Country { get; set; }
        public virtual Organizations Organizations { get; set; }
    }
}
